require('plugins.lualine')
-- require('plugins.copilot')
require('plugins.lspconfig')
require('plugins.treesitter')
require("plugins.indent")
require("plugins.luasnip")
require("plugins.telescope")
require('plugins.fterm')
require('plugins.comment')
require('plugins.color')
-- require('plugins.tabnine')
-- require('plugins.noice')
